/*
 * Decompiled with CFR 0.151.
 */
package com.m1zark.gts.enums;

public enum Abilities {
    Adaptability("Adaptability", "Powers up moves of the same type as the Pok\u00e9mon."),
    Aerilate("Aerilate", "Normal-type moves become Flying-type moves."),
    Aftermath("Aftermath", "Damages the attacker landing the finishing hit."),
    AirLock("Air Lock", "Eliminates the effects of weather."),
    Analytic("Analytic", "Boosts move power when the Pok\u00e9mon moves after the target."),
    AngerPoint("Anger Point", "Maxes the Attack stat after the Pok\u00e9mon takes a critical hit."),
    Anticipation("Anticipation", "Senses an opposing Pok\u00e9mon's dangerous moves."),
    ArenaTrap("Arena Trap", "Prevents opposing Pok\u00e9mon from fleeing."),
    AromaVeil("Aroma Veil", "Protects allies from attacks that effect their mental state."),
    AuraBreak("Aura Break", "The effects of \"Aura\" Abilities are reversed."),
    BadDreams("Bad Dreams", "Reduced the HP of sleeping opposing Pok\u00e9mon."),
    Battery("Battery", "Powers up ally Pok\u00e9mon\u00e2\u20ac\u2122s special moves."),
    BattleArmour("Battle Armour", "Protects the Pok\u00e9mon from critical hits."),
    BattleBond("Battle Bond", "Defeating an opposing Pok\u00e9mon strengthens the Pok\u00e9mon\u00e2\u20ac\u2122s bond with its Trainer, and it becomes Ash-Greninja. Water Shuriken gets more powerful."),
    BeastBoost("Beast Boost", "The Pok\u00e9mon boosts its most proficient stat each time it knocks out a Pok\u00e9mon."),
    Beserk("Beserk", "Boosts the Pok\u00e9mon\u00e2\u20ac\u2122s Sp. Atk stat when it takes a hit that causes its HP to become half or less."),
    BigPecks("Big Pecks", "Protects the Pok\u00e9mon from Defense-lowering attacks."),
    Blaze("Blaze", "Powers up Fire-type moves when the Pok\u00e9mon is in trouble."),
    Bulletproof("Bulletproof", "Protects the Pok\u00e9mon from some ball and bomb moves."),
    CheekPouch("Cheek Pouch", "Restores HP as well when the Pok\u00e9mon eats a Berry."),
    Chlorophyll("Chlorophyll", "Boosts the Pok\u00e9mon's Speed stat in sunshine."),
    ClearBody("Clear Body", "Prevents other Pok\u00e9mon from lowering its stats."),
    CloudNine("Cloud Nine", "Eliminates the effects of weather."),
    ColorChange("Color Change", "The Pok\u00e9mon's type becomes the type of the move used on it."),
    Comastose("Comastose", "It\u00e2\u20ac\u2122s always drowsing and will never wake up. It can attack without waking up."),
    Competitive("Competitive", "Boosts the Sp. Atk stat when a stat is lowered."),
    CompoundEyes("Compound Eyes", "Boosts the Pok\u00e9mon's accuracy."),
    Contrary("Contrary", "Makes stat changes have an opposite effect."),
    Corrosion("Corrosion", "The Pok\u00e9mon can poison the target even if it\u00e2\u20ac\u2122s a Steel or Poison type."),
    CursedBody("Cursed Body", "May disable a move used on the Pok\u00e9mon."),
    CuteCharm("Cute Charm", "Contact with the Pok\u00e9mon may cause infatuation."),
    Damp("Damp", "Prevents the use of self-destructing moves."),
    Dancer("Dancer", "When another Pok\u00e9mon uses a dance move, it can use a dance move following it regardless of its Speed."),
    DarkAura("Dark Aura", "Powers up each Pok\u00e9mon's Dark-type moves."),
    Dazzling("Dazzling", "Surprises the opposing Pok\u00e9mon, making it unable to attack using priority moves."),
    Defeatist("Defeatist", "Lowers stats when HP becomes half or less."),
    Defiant("Defiant", "Boosts the Pok\u00e9mon's Attack stat when its stats are lowered."),
    Disguise("Disguise", "Once per battle, the shroud that covers the Pok\u00e9mon can protect it from an attack."),
    Download("Download", "Adjusts power based on an opposing Pok\u00e9mon's stats."),
    Drizzle("Drizzle", "The Pok\u00e9mon makes it rain when it enters a battle."),
    Drought("Drought", "Turns the sunlight harsh when the Pok\u00e9mon enters a battle."),
    DrySkin("Dry Skin", "Reduces HP if it is hot. Water restores HP."),
    EarlyBird("Early Bird", "The Pok\u00e9mon awakens quickly from sleep."),
    EffectSpore("Effect Spore", "Contact may poison or cause paralysis or sleep."),
    ElectricSurge("Electric Surge", "Turns the ground into Electric Terrain when the Pok\u00e9mon enters a battle."),
    EmergencyExit("Emergency Exit", "The Pok\u00e9mon, sensing danger, switches out when its HP becomes half or less."),
    FairyAura("Fairy Aura", "Powers up each Pok\u00e9mon's Fairy-type moves."),
    Filter("Filter", "Reduces damage from super-effective attacks."),
    FlameBody("Flame Body", "Contact with the Pok\u00e9mon may burn the attacker."),
    FlareBoost("Flare Boost", "Powers up special attacks when the Pok\u00e9mon is burned."),
    FlashFire("Flash Fire", "Powers up the Pok\u00e9mon's Fire-type moves if it is hit by one."),
    FlowerGift("Flower Gift", "Powers up party Pok\u00e9mon when it is sunny."),
    FlowerVeil("Flower Veil", "Prevents lowering of ally Grass-type Pok\u00e9mon's stats."),
    Fluffy("Fluffy", "Halves the damage taken from moves that make direct contact, but doubles that of Fire-type moves."),
    Forecast("Forecast", "Castform transforms with the weather."),
    Forewarn("Forewarn", "Determines what moves an opposing Pok\u00e9mon has."),
    FriendGuard("Friend Guard", "Reduces damage done to allies."),
    Frisk("Frisk", "The Pok\u00e9mon can check an opposing Pok\u00e9mon's held item."),
    FullMetalBody("Full Metal Body", "Prevents other Pok\u00e9mon\u00e2\u20ac\u2122s moves or Abilities from lowering the Pok\u00e9mon\u00e2\u20ac\u2122s stats."),
    FurCoat("Fur Coat", "Halves damage from physical moves."),
    GaleWings("Gale Wings", "Gives priority to Flying-type moves."),
    Galvanize("Galvanize", "Normal-type moves become Electric-type moves. The power of those moves is boosted a little."),
    Gluttony("Gluttony", "Makes the Pok\u00e9mon use a held Berry earlier than usual."),
    Gooey("Gooey", "Contact with the Pok\u00e9mon lowers the attackers Speed stat."),
    GrassPelt("Grass Pelt", "Boosts the Defense stat in Grassy Terrain."),
    GrassySurge("Grassy Surge", "Turns the ground into Grassy Terrain when the Pok\u00e9mon enters a battle."),
    Guts("Guts", "Boosts the Attack stat if the Pok\u00e9mon has a status condition."),
    Harvest("Harvest", "May create another Berry after one is used."),
    Healer("Healer", "Sometimes heals an ally's status condition."),
    Heatproof("Heatproof", "Weakens the power of Fire-type moves."),
    HeavyMetal("Heavy Metal", "Doubles the Pok\u00e9mon's weight."),
    HoneyGather("Honey Gather", "The Pok\u00e9mon may gather Honey from somewhere."),
    HugePower("Huge Power", "Boosts the Pok\u00e9mon's Attack stat."),
    Hustle("Hustle", "Boosts the Attack stat, but lowers accuracy."),
    Hydration("Hydration", "Heals status conditions if it is raining."),
    HyperCutter("Hyper Cutter", "Prevents other Pok\u00e9mon from lowering its Attack stat."),
    IceBody("Ice Body", "The Pok\u00e9mon gradually regains HP in a hailstorm."),
    Illuminate("Illuminate", "Raises the likelihood of meeting wild Pok\u00e9mon."),
    Illusion("Illusion", "Comes out disguised as the Pok\u00e9mon in the party's last spot."),
    Immunity("Immunity", "Prevents the Pok\u00e9mon from getting poisoned."),
    Imposter("Imposter", "The Pok\u00e9mon transforms itself into the Pok\u00e9mon it is facing."),
    Infiltrator("Infiltrator", "Passes through the opposing Pok\u00e9mon's barrier and strikes."),
    InnardsOut("Innards Out", "Damages the attacker landing the finishing hit by the amount equal to its last HP."),
    InnerFocus("Inner Focus", "Protects the Pok\u00e9mon from flinching."),
    Insomnia("Insomnia", "Prevents the Pok\u00e9mon from falling asleep."),
    Intimidate("Intimidate", "Lowers the opposing Pok\u00e9mon's Attack stat."),
    IronBarbs("Iron Barbs", "Inflicts damage to the attacker on contact."),
    IronFist("Iron Fist", "Powers up punching moves."),
    Justified("Justified", "Boosts the Attack stat when it's hit by a Dark-type move."),
    KeenEye("Keen Eye", "Prevents other Pok\u00e9mon from lowering accuracy."),
    Klutz("Klutz", "The Pok\u00e9mon can't use any held items."),
    LeafGuard("Leaf Guard", "Prevents status conditions in sunny weather."),
    Levitate("Levitate", "Gives full immunity to all Ground-type moves."),
    LightMetal("Light Metal", "Halves the Pok\u00e9mon's weight."),
    LightningRod("Lightning Rod", "Draws in all Electric-type moves to boost its Sp. Atk stat."),
    Limber("Limber", "Protects the Pok\u00e9mon from paralysis."),
    LiquidOoze("Liquid Ooze", "Damages attackers using any draining move."),
    LiquidVoice("Liquid Voice", "All sound-based moves become Water-type moves"),
    LongReach("Long Reach", "The Pok\u00e9mon uses its moves without making contact with the target."),
    MagicBounce("Magic Bounce", "Reflects status moves."),
    MagicGuard("Magic Guard", "The Pok\u00e9mon only takes damage from attacks."),
    Magician("Magician", "The Pok\u00e9mon steals the held item of a Pok\u00e9mon it hits with a move."),
    MagmaArmor("Magma Armor", "Prevents the Pok\u00e9mon from becoming frozen."),
    MagnetPull("Magnet Pull", "Prevents Steel-type Pok\u00e9mon from escaping."),
    MarvelScale("Marvel Scale", "Boosts the Defense stat if the Pok\u00e9mon has a status condition."),
    MegaLauncher("Mega Launcher", "Powers up aura and pulse moves."),
    Merciless("Merciless", "The Pok\u00e9mon\u00e2\u20ac\u2122s attacks become critical hits if the target is poisoned."),
    Minus("Minus", "Boosts the Sp. Atk stat if another Pok\u00e9mon has Plus or Minus."),
    MistySurge("Misty Surge", "Turns the ground into Misty Terrain when the Pok\u00e9mon enters a battle."),
    MoldBreaker("Mold Breaker", "Moves can be used on the target regardless of its Abilities."),
    Moody("Moody", "Raises one stat and lowers another."),
    MotorDrive("Motor Drive", "Boosts the Speed stat when it's hit by an Electric-type move."),
    Moxie("Moxie", "Boosts the Attack stat after knocking out any Pok\u00e9mon."),
    Multiscale("Multiscale", "Reduces damage the Pok\u00e9mon takes when its HP is full."),
    Multitype("Multitype", "Changes the Pok\u00e9mon's type to match the Plate it holds."),
    Mummy("Mummy", "Contact with the Pok\u00e9mon spreads this "),
    NaturalCure("Natural Cure", "All status conditions heal when the Pok\u00e9mon switches out."),
    NoGuard("No Guard", "Ensures attacks by or against the Pok\u00e9mon land."),
    Normalize("Normalize", "All the Pok\u00e9mon's moves become Normal type."),
    Oblivious("Oblivious", "Keeps the Pok\u00e9mon from being infatuated or falling for taunts."),
    Overcoat("Overcoat", "Protects the Pok\u00e9mon from things like sand, hail and powder."),
    Overgrow("Overgrow", "Powers up Grass-type moves when the Pok\u00e9mon is in trouble."),
    OwnTempo("Own Tempo", "Prevents the Pok\u00e9mon from becoming confused."),
    ParentalBond("Parental Bond", "Parent and child attack together"),
    Pickpocket("Pickpocket", "Steals an item from an attacker that made direct contact."),
    Pickup("Pickup", "The Pok\u00e9mon may pick up items."),
    Pixilate("Pixilate", "Normal-type moves become Fairy-type moves."),
    Plus("Plus", "Boosts the Sp. Atk stat if another Pok\u00e9mon has Plus or Minus."),
    PoisonHeal("Poison Heal", "Restores HP if the Pok\u00e9mon is poisoned."),
    PoisonPoint("Poison Point", "Contact with the Pok\u00e9mon may poison the attacker."),
    PoisonTouch("Poison Touch", "May poison a target when the Pok\u00e9mon makes contact."),
    PowerConstruct("Power Construct", "Other Cells gather to aid when its HP becomes half or less. Then the Pok\u00e9mon changes its form to Complete Forme."),
    PowerOfAlchemy("Power Of Alchemy", "The Pok\u00e9mon copies the Ability of a defeated ally."),
    Prankster("Prankster", "Gives priority to a status move."),
    Pressure("Pressure", "The Pok\u00e9mon raises opposing Pok\u00e9mon's PP usage."),
    PrismArmor("Prism Armor", "Reduces the power of super-effective attacks taken."),
    Protean("Protean", "Changes the Pok\u00e9mon's type to the type of the move it's using."),
    PsychicSurge("Psychic Surge", "Turns the ground into Psychic Terrain when the Pok\u00e9mon enters a battle."),
    PurePower("Pure Power", "Boosts the Pok\u00e9mon's Attack stat."),
    QueenlyMajesty("Queenly Majesty", "Its majesty pressures the opposing Pok\u00e9mon, making it unable to attack using priority moves."),
    QuickFeet("Quick Feet", "Boosts the Speed stat if the Pok\u00e9mon has a status condition."),
    RainDish("Rain Dish", "The Pok\u00e9mon gradually regains HP in rain."),
    Rattled("Rattled", "Some move types scare it and boost it Speed stat."),
    Receiver("Receiver", "The Pok\u00e9mon copies the Ability of a defeated ally."),
    Reckless("Reckless", "Powers up moves that have recoil damage."),
    Refrigerate("Refrigerate", "Normal-type moves become Ice-type moves."),
    Regenerator("Regenerator", "Restores a little HP when withdrawn from battle."),
    Rivalry("Rivalry", "Deals more damage to Pok\u00e9mon of the same gender."),
    RKSSystem("RKS System", "Changes the Pok\u00e9mon\u00e2\u20ac\u2122s type to match the memory disc it holds."),
    RockHead("Rock Head", "Protects the Pok\u00e9mon from recoil damage."),
    RoughSkin("Rough Skin", "Inflicts damage to the attacker on contact."),
    RunAway("Run Away", "Enables a sure getaway from wild Pok\u00e9mon."),
    SandForce("Sand Force", "Boosts certain moves' power in a sandstorm."),
    SandRush("Sand Rush", "Boosts the Pok\u00e9mon's Speed stat in a sandstorm."),
    SandStream("Sand Stream", "The Pok\u00e9mon summons a sandstorm in battle."),
    SandVeil("Sand Veil", "Boosts the Pok\u00e9mon's evasion in a sandstorm."),
    SapSipper("Sap Sipper", "Boosts the Attack stat when hit by a Grass-type move."),
    Schooling("Schooling", "When it has a lot of HP, the Pok\u00e9mon forms a powerful school. It stops schooling when its HP is low."),
    Scrappy("Scrappy", "Makes Normal- and Fighting-type moves hit Ghost-type Pok\u00e9mon."),
    SereneGrace("Serene Grace", "Boosts the likelihood of additional effects occurring."),
    ShadowShield("Shadow Shield", "Reduces the amount of damage the Pok\u00e9mon takes while its HP is full."),
    ShadowTag("Shadow Tag", "Prevents opposing Pok\u00e9mon from escaping."),
    ShedSkin("Shed Skin", "The Pok\u00e9mon may heal its own status conditions."),
    SheerForce("Sheer Force", "Removes additional effects to increase move damage."),
    ShellArmour("Shell Armour", "Protects the Pok\u00e9mon from critical hits."),
    ShieldsDown("Shields Down", "When its HP becomes half or less, the Pok\u00e9mon\u00e2\u20ac\u2122s shell breaks and it becomes aggressive."),
    ShieldDust("Shield Dust", "Blocks the additional effects of attacks taken."),
    Simple("Simple", "The Pok\u00e9mon is prone to wild stat changes."),
    SkillLink("Skill Link", "Increases the number of times multi-strike moves hit."),
    SlowStart("Slow Start", "Temporarily halves the Pok\u00e9mon's Attack and Speed stats."),
    SlushRush("Slush Rush", "Boosts the Pok\u00e9mon\u00e2\u20ac\u2122s Speed stat in a hailstorm."),
    Sniper("Sniper", "Powers up moves if they become critical hits."),
    SnowCloak("Snow Cloak", "Boosts evasion in a hailstorm."),
    SnowWarning("Snow Warning", "The Pok\u00e9mon summons a hailstorm when it enters a battle."),
    SolarPower("Solar Power", "Boosts the Sp. Atk stat in sunny weather, but HP decreases."),
    SolidRock("Solid Rock", "Reduces damage from super-effective attacks."),
    SoulHeart("Soul Heart", "Boosts its Sp. Atk stat every time a Pok\u00e9mon faints."),
    Soundproof("Soundproof", "Gives full immunity to all sound-based moves."),
    SpeedBoost("Speed Boost", "Its Speed stat is gradually boosted."),
    Stakeout("Stakeout", "Doubles the damage dealt to the target\u00e2\u20ac\u2122s replacement if the target switches out."),
    Stall("Stall", "The Pok\u00e9mon moves after all other Pok\u00e9mon do."),
    Stamina("Stamina", "Boosts the Defense stat when hit by an attack."),
    StanceChange("Stance Change", "The Pok\u00e9mon changes form depending on how it battles."),
    Static("Static", "Contact with the Pok\u00e9mon may cause paralysis."),
    Steadfast("Steadfast", "Boosts the Speed stat each time the Pok\u00e9mon flinches."),
    Steelworker("Steelworker", "Powers up Steel-type moves."),
    Stench("Stench", "The stench may cause the target to flinch."),
    StickyHold("Sticky Hold", "Protects the Pok\u00e9mon from item theft."),
    StormDrain("Storm Drain", "Draws in all Water-type moves to boost its Sp. Atk stat."),
    StrongJaw("Strong Jaw", "The Pok\u00e9mon's strong jaw gives it tremendous biting power."),
    Sturdy("Sturdy", "It cannot be knocked out with one hit."),
    SuctionCups("Suction Cups", "Negates all moves and items that force switching out."),
    SuperLuck("Super Luck", "Boosts the critical-hit ratios of moves."),
    SurgeSurfer("Surge Surfer", "Doubles the Pok\u00e9mon\u00e2\u20ac\u2122s Speed stat on Electric Terrain."),
    Swarm("Swarm", "Powers up Bug-type moves when the Pok\u00e9mon is in trouble."),
    SweetVeil("Sweet Veil", "Prevents itself and ally Pok\u00e9mon from falling asleep."),
    SwiftSwim("Swift Swim", "Boosts the Pok\u00e9mon's Speed stat in rain."),
    Symbiosis("Symbiosis", "The Pok\u00e9mon can pass an item to an ally."),
    Synchronize("Synchronize", "Passes poison, paralyze, or burn to the Pok\u00e9mon that inflicted it."),
    TangledFeet("Tangled Feet", "Raises evasion if the Pok\u00e9mon is confused."),
    TanglingHair("Tangling Hair", "Contact with the Pok\u00e9mon lowers the attacker\u00e2\u20ac\u2122s Speed stat."),
    Technician("Technician", "Powers up the Pok\u00e9mon's weaker moves."),
    Telepathy("Telepathy", "Anticipates an ally's attack an dodges it."),
    Teravolt("Teravolt", "Moves can be used on the target regardless of its Abilities."),
    ThickFat("Thick Fat", "Boosts resistance to Fire- and Ice-type moves."),
    TintedLens("Tinted Lens", "Powers up \"not very effective\" moves."),
    Torrent("Torrent", "Powers up Water-type moves when the Pok\u00e9mon is in trouble."),
    ToughClaws("Tough Claws", "Powers up moves hat make direct contact."),
    ToxicBoost("Toxic Boost", "Powers up physical attacks when the Pok\u00e9mon is poisoned."),
    Trace("Trace", "The Pok\u00e9mon copies an opposing Pok\u00e9mon's "),
    Triage("Triage", "Gives priority to a healing move."),
    Truant("Truant", "The Pok\u00e9mon can't attack on consecutive turns."),
    Turboblaze("Turboblaze", "Moves can be used on the target regardless of its Abilities."),
    Unaware("Unaware", "Ignores the opposing Pok\u00e9mon's stat changes."),
    Unburden("Unburden", "Boosts the Speed stat if its held item is used or lost."),
    Unnerve("Unnerve", "Unnerves opposing Pok\u00e9mon and makes them unable to eat Berries."),
    VictoryStar("Victory Star", "Boosts of the accuracy of its allies and itself."),
    VitalSpirit("Vital Spirit", "Prevents the Pok\u00e9mon from falling asleep."),
    VoltAbsorb("Volt Absorb", "Restores HP if hit by an Electric-type move."),
    WaterAbsorb("Water Absorb", "Restores HP if hit by a Water-type move."),
    WaterBubble("Water Bubble", "Lowers the power of Fire-type moves done to the Pok\u00e9mon and prevents the Pok\u00e9mon from getting a burn."),
    WaterCompaction("Water Compaction", "Boosts the Pok\u00e9mon\u00e2\u20ac\u2122s Defense stat sharply when hit by a Water-type move."),
    WaterVeil("Water Veil", "Prevents the Pok\u00e9mon from getting a burn."),
    WeakArmor("Weak Armor", "Physical attacks lower its Defense stat and raise its Speed stat."),
    WhiteSmoke("White Smoke", "Prevents other Pok\u00e9mon from lowering its stats."),
    WimpOut("Wimp Out", "The Pok\u00e9mon cowardly switches out when its HP becomes half or less."),
    WonderGuard("Wonder Guard", "Only super-effective moves will hit."),
    WonderSkin("Wonder Skin", "Makes status moves more likely to miss."),
    ZenMode("Zen Mode", "Changes the Pok\u00e9mon's shape when HP is half or less."),
    ComingSoon("Coming Soon!", "This Ability has not been coded yet, but it will be soon!");

    private String description;
    private String name;

    private Abilities(String name, String description) {
        this.name = name;
        this.description = description;
    }

    public String getDescription() {
        return this.description;
    }

    public String getName() {
        return this.name;
    }
}

